"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-28
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gst_enabled', sa.Boolean(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('parsing', 'review', 'committed', 'discarded', name='import_status', native_enum=False), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_org_id'), 'import_jobs', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('channel', sa.Enum('email', name='notification_channel', native_enum=False), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status', native_enum=False), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notifications_dedupe_key')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_table('recurrence_rules',
    sa.Column('freq', sa.Enum('weekly', name='recurrence_freq', native_enum=False), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('byweekday', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrence_rules_org_id'), 'recurrence_rules', ['org_id'], unique=False)
    op.create_table('students',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'churned', name='student_status', native_enum=False), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_org_id'), 'students', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'coach', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('credit_packs',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('price_per_session', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_packs_org_id'), 'credit_packs', ['org_id'], unique=False)
    op.create_index(op.f('ix_credit_packs_student_id'), 'credit_packs', ['student_id'], unique=False)
    op.create_table('guardians',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_org_id'), 'guardians', ['org_id'], unique=False)
    op.create_index(op.f('ix_guardians_student_id'), 'guardians', ['student_id'], unique=False)
    op.create_table('invoices',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', name='invoice_status', native_enum=False), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'number', name='uq_invoices_org_number')
    )
    op.create_index(op.f('ix_invoices_org_id'), 'invoices', ['org_id'], unique=False)
    op.create_index(op.f('ix_invoices_student_id'), 'invoices', ['student_id'], unique=False)
    op.create_table('lessons',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('recurrence_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='lesson_status', native_enum=False), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=512), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('credit_deducted', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrence_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_coach_id'), 'lessons', ['coach_id'], unique=False)
    op.create_index(op.f('ix_lessons_org_id'), 'lessons', ['org_id'], unique=False)
    op.create_index(op.f('ix_lessons_recurrence_id'), 'lessons', ['recurrence_id'], unique=False)
    op.create_index(op.f('ix_lessons_starts_at'), 'lessons', ['starts_at'], unique=False)
    op.create_index(op.f('ix_lessons_student_id'), 'lessons', ['student_id'], unique=False)
    op.create_table('share_links',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_share_links_token')
    )
    op.create_index(op.f('ix_share_links_org_id'), 'share_links', ['org_id'], unique=False)
    op.create_index(op.f('ix_share_links_student_id'), 'share_links', ['student_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('purchase', 'deduct', 'refund', 'adjust', name='ledger_reason', native_enum=False), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['credit_packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_lesson_id'), 'credit_ledger', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_org_id'), 'credit_ledger', ['org_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_pack_id'), 'credit_ledger', ['pack_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_student_id'), 'credit_ledger', ['student_id'], unique=False)
    op.create_table('lesson_notes',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('text', 'voice', name='note_source', native_enum=False), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_notes_lesson_id'), 'lesson_notes', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_notes_org_id'), 'lesson_notes', ['org_id'], unique=False)
    op.create_index(op.f('ix_lesson_notes_student_id'), 'lesson_notes', ['student_id'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'transfer', 'other', name='payment_method', native_enum=False), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('paid', 'due', name='payment_status', native_enum=False), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['credit_packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_org_id'), 'payments', ['org_id'], unique=False)
    op.create_index(op.f('ix_payments_pack_id'), 'payments', ['pack_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###

    # --- Optional Postgres RLS (defence-in-depth) ---------------------------
    # App-level tenant scoping (app.core.deps.scoped / current_org) is the
    # primary enforcement. To additionally enforce isolation at the DB layer,
    # set `app.current_org` per connection and enable RLS, e.g.:
    #
    #   for table in TENANT_TABLES:
    #       op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    #       op.execute(
    #           f"CREATE POLICY {table}_org_isolation ON {table} "
    #           f"USING (org_id = current_setting('app.current_org')::uuid)"
    #       )
    #
    # Left disabled for the foundation so seed/admin scripts run unimpeded.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pack_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_org_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lesson_notes_student_id'), table_name='lesson_notes')
    op.drop_index(op.f('ix_lesson_notes_org_id'), table_name='lesson_notes')
    op.drop_index(op.f('ix_lesson_notes_lesson_id'), table_name='lesson_notes')
    op.drop_table('lesson_notes')
    op.drop_index(op.f('ix_credit_ledger_student_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_pack_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_org_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_lesson_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_share_links_student_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_org_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_lessons_student_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_starts_at'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_recurrence_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_org_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_coach_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_invoices_student_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_org_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_guardians_student_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_org_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_credit_packs_student_id'), table_name='credit_packs')
    op.drop_index(op.f('ix_credit_packs_org_id'), table_name='credit_packs')
    op.drop_table('credit_packs')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_org_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_recurrence_rules_org_id'), table_name='recurrence_rules')
    op.drop_table('recurrence_rules')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_import_jobs_org_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_table('organizations')
    # ### end Alembic commands ###
